service: express-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-2

functions:
  server:
    handler: server.handler

    events:
      - http:
          path: /
          method: ANY
          cors: false
      - http:
          path: /students
          method: ANY
          cors: false
      - http:
          path: /courses
          method: ANY
          cors: false
