service: express-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-2

functions:
  getStudents:
    handler: ./lambdas/Student/getStudents.handler
    events:
      - http:
          path: /students
          method: GET
